app = "late-moonrise-806"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "alembic upgrade head"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
